### ISSUE TITLE
could not import the project in studio

### ISSUE THREAD

**Issue by DravitLochan** [Catrobat/Timesheet#3]
I cloned the repo at my local and tried importing from the master but here was no framework detected. any help?

**Comment by DravitLochan** [comment]
is linux mandatory?

**Comment by Iseratho** [comment]
No it works on MacOs and Windows too.
The binaries can be found on: https://developer.atlassian.com/docs/getting-started/downloads

**Comment by DravitLochan** [comment]
thanks.
